### ISSUE TITLE
Recursive ReadWrite lock

### ISSUE THREAD

**Issue by MapleWheels** [MapleWheels/ModdingToolkit#3]
Caused by the CleanupReferences() function entering a lock already in use by the code calling it. Causes the error shown here: PeasantFoundry/Mechtrauma#72 .

```csharp
[CL CS ERROR] System.Threading.LockRecursionException: Recursive write lock acquisitions not allowed in this mode.
at System.Threading.ReaderWriterLockSlim.TryEnterWriteLockCore(TimeoutTracker timeout)
at ModdingToolkit.AssemblyManager.CleanupReference(AssemblyLoadContext ctx)
at System.Runtime.Loader.AssemblyLoadContext.RaiseUnloadEvent()
at System.Runtime.Loader.AssemblyLoadContext.InitiateUnload()
at System.Runtime.Loader.AssemblyLoadContext.Unload()
at ModdingToolkit.AssemblyManager.BeginDispose()
at ModdingToolkit.PluginHelper.UnloadAssemblies()
at ModdingToolkit.Bootloader.Stop()
at Barotrauma.ACsMod.Dispose() in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\LuaCs\Cs\ACsMod.cs:line 36
```

**Comment by MapleWheels** [comment]
Fixed in version 0.3.7.
